version: '3'

services:
  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
        - "6379:6379"
    volumes:
        - /data/redis:/data
  daily_word_bot_app:
    build: .
    image: rooom13:deutschlerne_bot
    container_name: deutschlerne_bot
    env_file:
      - .env
    links: 
      - redis
    depends_on:
      - "redis"
    ports:
      - "8443:8443"
    restart: always
